### ISSUE TITLE
Crash when using sld2gdx with lwjgl3 backend.

### ISSUE THREAD

**Issue by rafaskb** [electronstudio/sdl2gdx#12]
Code:
```java
Controllers.addListener(this);

// OR

SDL2ControllerManager manager = new SDL2ControllerManager();
manager.addListener(this);  
```

Exception:
```
Exception in thread "main" com.badlogic.gdx.utils.GdxRuntimeException: Error creating controller manager: com.badlogic.gdx.controllers.lwjgl3.Lwjgl3ControllerManager
	at com.badlogic.gdx.controllers.Controllers.initialize(Controllers.java:120)
	at com.badlogic.gdx.controllers.Controllers.addListener(Controllers.java:59)
	at com.rafaskoberg.controllerscanner.ControllerScanner.init(ControllerScanner.java:159)
	at com.rafaskoberg.controllerscanner.ControllerScanner.render(ControllerScanner.java:189)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Window.update(Lwjgl3Window.java:399)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.loop(Lwjgl3Application.java:137)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:111)
	at com.rafaskoberg.controllerscanner.desktop.ControllerScannerDesktop.main(ControllerScannerDesktop.java:14)
Caused by: com.badlogic.gdx.utils.reflect.ReflectionException: Class not found: com.badlogic.gdx.controllers.lwjgl3.Lwjgl3ControllerManager
	at com.badlogic.gdx.utils.reflect.ClassReflection.forName(ClassReflection.java:30)
	at com.badlogic.gdx.controllers.Controllers.initialize(Controllers.java:117)
	... 7 more
Caused by: java.lang.ClassNotFoundException: com.badlogic.gdx.controllers.lwjgl3.Lwjgl3ControllerManager
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at com.badlogic.gdx.utils.reflect.ClassReflection.forName(ClassReflection.java:28)
	... 8 more
```

I'm running libGDX 1.9.9 using the lwjgl3 backend on a macOS 10.14.4 computer.

**Comment by electronstudio** [comment]
sdl2gdx wasn't compatible with lwjgl3.  This should have been fixed in https://github.com/electronstudio/sdl2gdx/commit/bc3e4360dd63e8813b7ce68867e58598ec971c12 which will be in the 1.0.3 release.  In the meantime you could just copy that single class from the commit into your code.

**Comment by electronstudio** [comment]
OK I pushed out 1.0.3 so should be fixed.

**Comment by rafaskb** [comment]
That fixes it, thanks! 😁
