### ISSUE TITLE
Error getting list of Controllers

### ISSUE THREAD

**Issue by SteveSmith16384** [electronstudio/sdl2gdx#19]
Hi.  After changing my build.gradle as per the section "For a LibGDX desktop project" in the readme, I get the following error & stack trace when I call "Controllers.getControllers();" in my code:-

Exception in thread "LWJGL Application" com.badlogic.gdx.utils.GdxRuntimeException: Error creating controller manager: com.badlogic.gdx.controllers.desktop.DesktopControllerManager
	at com.badlogic.gdx.controllers.Controllers.initialize(Controllers.java:120)
	at com.badlogic.gdx.controllers.Controllers.getControllers(Controllers.java:51)
	at com.scs.splitscreenfps.ControllerManager.checkForControllers(ControllerManager.java:29)
	at com.scs.splitscreenfps.pregame.PreGameScreen.render(PreGameScreen.java:30)
	at com.scs.splitscreenfps.BillBoardFPS_Main.render(BillBoardFPS_Main.java:25)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:225)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:126)
Caused by: com.badlogic.gdx.utils.reflect.ReflectionException: Class not found: com.badlogic.gdx.controllers.desktop.DesktopControllerManager
	at com.badlogic.gdx.utils.reflect.ClassReflection.forName(ClassReflection.java:30)
	at com.badlogic.gdx.controllers.Controllers.initialize(Controllers.java:117)
	... 6 more
Caused by: java.lang.ClassNotFoundException: com.badlogic.gdx.controllers.desktop.DesktopControllerManager
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Unknown Source)
	at com.badlogic.gdx.utils.reflect.ClassReflection.forName(ClassReflection.java:28)
	... 7 more

Do I need to make any more changes to my project in order to use sdl2gdx?

Thanks.

**Comment by electronstudio** [comment]
Sounds like you are missing
       `compile "com.badlogicgames.gdx:gdx-controllers:$gdxVersion"`
or
       `compile "uk.co.electronstudio.sdl2gdx:sdl2gdx:1.0.+"`

You also need gdx-controllers in your core project, but if you were missing that it wouldn't compile.

I made a demo project using latest GDX setup to check it works: https://github.com/electronstudio/sdl2gdx-test

**Comment by SteveSmith16384** [comment]
Thanks for the response.  I've managed to get it to work by copying bits of the build.gradle file from the projecty you mentioned.  Good work, and thanks.
